### ISSUE TITLE
Screen reported as always on

### ISSUE THREAD

**Issue by acateon** [tofuSCHNITZEL/rpi-screenbrightness-mqtt#1]
First of all thanks for a great project!

Small issue with the touch screen blanking out via:

xset s 120
xset dpms 120 120 120 

The light entity in HA always reports the backlight as on even though the backlight is off by timing out from the settings above.

Would be great if the readme could contain if it depends on xscreensaver or specific X settings with dmps / s.

**Comment by tofuSCHNITZEL** [comment]
sorry I slapped this together pretty quickly... since this sends periodic updates over mqtt the issue must be with the rpi_brightness package not working together with the windowmanager... maybe you should ask there: https://github.com/linusg/rpi-backlight
