### ISSUE TITLE
Service fails to start

### ISSUE THREAD

**Issue by Poli88** [tofuSCHNITZEL/rpi-screenbrightness-mqtt#5]
Hi, if I run the command `sudo systemctl status rpi_screenbrightness_mqtt` , the results is FAILURE (see first pic below)
![image](https://user-images.githubusercontent.com/73400662/175774384-02627fe2-93eb-45cd-8c35-5862c251750d.png)

And this is the result of running the command `sudo journalctl -u rpi_screenbrightness_mqtt.service` :
![image](https://user-images.githubusercontent.com/73400662/175774441-8f77b601-5d0a-4989-a7e3-ac6df604c1ca.png)

Can you please help me ?

**Comment by tofuSCHNITZEL** [comment]
On what hardware are you trying to run it?
Can you try to run https://github.com/linusg/rpi-backlight stand alone and see if it works?

**Comment by Poli88** [comment]
I'm trying to run it on a RaspberryPi 4b with original 7" touchscreen display.

I tried to run the two commands of your link:
![image](https://user-images.githubusercontent.com/73400662/175780912-f2f6a68a-babb-4ddb-8ec9-ef9613c31b45.png)

but if I try to launch the `rpi-backlight-gui` command, I get error:
![image](https://user-images.githubusercontent.com/73400662/175781037-3e1f248d-0907-4bdd-ab89-15308c277730.png)

**Comment by tofuSCHNITZEL** [comment]
Hm not sure... Maybe you should ask there...

**Comment by sepiroh** [comment]
@Poli88 I ran manually the contents of install.sh and found a problem with the permissions. 

Edit the file /rpi-screenbrightness-mqtt/install.sh and search for the line `chmod 644 /etc/systemd/system/rpi_screenbrightness_mqtt.service`, change 644 with 666 and it will work.

**Comment by joalsaru** [comment]
@Poli88 I had issues with the password because it included a % character. I used a password without special characters and worked.
