### ISSUE TITLE
How to add hostname in topic?

### ISSUE THREAD

**Issue by Dexter0007** [tofuSCHNITZEL/rpi-screenbrightness-mqtt#6]
Hi, I need set hostname in topic to control multiple Rpi's so I added this in conf file:

`state_topic =  ${HOSTNAME}/state/power`

but mqtt stops sending anything after that.
How can do that?

**Comment by tofuSCHNITZEL** [comment]
Hi,
sorry I totally overlooked you post. this is now possible in version 0.6.0:
https://github.com/tofuSCHNITZEL/rpi-screenbrightness-mqtt/releases/tag/v0.6.0

cheers
