### ISSUE TITLE
Integration of Waveshare screen brightness controls.

### ISSUE THREAD

**Issue by stav242** [tofuSCHNITZEL/rpi-screenbrightness-mqtt#8]
Hi,
i was running the 5" Waveshare DSI screen on my RPi and you script was working great.

ive just upgraded the screen to a 10.1" waveshare model, and it seems they might have different method of brightness controls.
they have software to manually control and mention it can be controlled over the command line.

would you be able to integrate this into you code ?
https://github.com/waveshareteam/Waveshare-DSI-LCD/tree/main/Backlight/BL-32bit

**Comment by tofuSCHNITZEL** [comment]
Hi,
this script only "wraps" around another python lib that actually controls the backlight. (https://github.com/linusg/rpi-backlight)
so the best thing would be if they could add support for it.. but this is probably also not that easy since waveshare only published a binary file to control the backlight and not source code...
So I think maybe I can try to add a detection to my script if the "[WS_xinchDSI_Backlight_armhf](https://github.com/waveshareteam/Waveshare-DSI-LCD/blob/main/Backlight/BL-32bit/WS_xinchDSI_Backlight_armhf)" is present and then send commands there instead...
but I will need you help since I cannot test it with my hardware... could you please tell me what commands [WS_xinchDSI_Backlight_armhf](https://github.com/waveshareteam/Waveshare-DSI-LCD/blob/main/Backlight/BL-32bit/WS_xinchDSI_Backlight_armhf) accepts? (maybe there is a help displayed if you call it)

**Comment by stav242** [comment]
Hi,

bear with me as im not a programmer...

the waveshare screen i have has this wiki page.
https://www.waveshare.com/wiki/10.1inch_DSI_LCD_(C)

there is a section on the page. would this be what your looking for ?
-----

In addition, you can also input the following commands to control the
backlight brightness in the terminal:

echo X | sudo tee /sys/class/backlight/*/brightness

X indicates any number from 0 to 255. 0 means the backlight is the darkest,
and 255 means the backlight is the brightest. For example:

echo 100 | sudo tee /sys/class/backlight/*/brightness
echo 0 | sudo tee /sys/class/backlight/*/brightness
echo 255 | sudo tee /sys/class/backlight/*/brightness

**Comment by stav242** [comment]
just realised in running a RPi 3+ with `Jessie`, and this software may only
be for For Bookworm and Bullseye System

i am planning to upgrade the hardware soon, - next week, so will be
swapping to a later software version and can retest then.

**Comment by tofuSCHNITZEL** [comment]
> echo X | sudo tee /sys/class/backlight/*/brightness X indicates any number from 0 to 255. 0 means the backlight is the darkest, and 255 means the backlight is the brightest. For example: echo 100 | sudo tee /sys/class/backlight/*/brightness echo 0 | sudo tee /sys/class/backlight/*/brightness echo 255 | sudo tee /sys/class/backlight/*/brightness

I think this is looks exactly like what the python library I use does... so maybe it should work with this display also.
I don't have such a display so I also cannot test how it works and how the backlight control executable waveshare provides works (or expects to be used)

**Comment by stav242** [comment]
Ok. I'll look into my config and setup a bit more.

**Comment by stav242** [comment]
Hi,
just checking back in...

ive moved my 10" waveshare DSI screen to a RPi4 now (was on RPi3 and was
struggling with display a full screen of active content) ... and i opted
for the latest Debian 12 (bookworm) release - as it seems to require less
config changes to get the screen and touch functionality working.
i now have a brightness function on the screen layout editor - which works.

but when i try to install you code o enable MQTT control, i am getting some
errors.
running `sudo ./rpi-screenbrightness-mqtt/install.sh`
- see attached pic.

is you code compatible with Bookworm ?
is there anything i need to do differently ?

[image: image.png]

thanks.
Stuart.

**Comment by tofuSCHNITZEL** [comment]
sorry there is no picture visible... what is the error you get?

**Comment by stav242** [comment]
Sorry copy and paste looses the formatting below.

It looks like an error the with pip setup.py line, I removed that and it
completed.

I have it working now,

..but the script and instructions didn't quite work for me.

-----
***@***.***:- S sudo./rpi-screenbrightness-mqtt/install.sh Installing
dependencies... ========================== Hit:1
http://deb.debian.org/debian bookworm InRelease Hit:2
http://deb.debian.org/debian-security bookworm-security InRelease Hit:3
http://archive.raspberrypi.com/debian bookworm InRelease Hit:4
http://deb.debian.org/debian bookworm-updates InRelease python3 is already
the newest version (3.11.2-1+b1). python3-pip is already the newest version
(23.0.1+dfsg-1+rpt1). git is already the newest version
(1:2.39.5-0+deb12u1). The following packages were automatically installed
and are no longer required: chromium-browser chromium-browser-110n
chromium-codecs-ffmpeg-extra Use 'sudo apt autoremove' to remove them. 0
upgraded, @ newly installed, @ to remove and @ not upgraded. error:
externally-managed-environment This environment is externally managed To
install Python packages system-wide, try apt install python3-xyz, where xyz
is the package you are trying to install. If you wish to install a
non-Debian-packaged Python package, create a virtual environment using
python3 -m venv path/to/venv. Then use path/to/venv/bin/python and
path/to/venv/bin/pip. Make sure you have python3-full installed. For more
information visit http://rptl.io/venv note: If you believe this is a
mistake, please contact your Python installation or Python installation or
0S, by passing --break-system-packages. ur hint: See PEP 668 for the
detailed specification.

**Comment by tofuSCHNITZEL** [comment]
I have updated the repo to use the modern pyproject.toml instead of the legacy setup.py and also added home assistant discovery... if you want - you can try the install again with version 0.7.0

**Comment by stav242** [comment]
ok, thank you, ill check and confirm back.

**Comment by stav242** [comment]
still getting the same error. ?

![image](https://github.com/user-attachments/assets/c232db16-0a6a-4a86-a74e-1cf1176f4ee5)

![image](https://github.com/user-attachments/assets/1c74a77e-011e-4f63-a37d-b46fae3aba00)

**Comment by tofuSCHNITZEL** [comment]
Is it a normal os install? I tried it on my rpi and I don't get this error.
"externally managed environments" sounds like something with your install...

**Comment by stav242** [comment]
ok, just did a quick search and this was suggested..

sudo mv /usr/lib/python3.11/EXTERNALLY-MANAGED /usr/lib/python3.11/EXTERNALLY-MANAGED.old
(Ref : https://stackoverflow.com/questions/75608323/how-do-i-solve-error-externally-managed-environment-every-time-i-use-pip-3)

seems to have fixed the error.

**Comment by tofuSCHNITZEL** [comment]
Great that you figured it out!

**Comment by stav242** [comment]
many thanks. hopefully thats usefull for others. all working now.
